### ISSUE TITLE
Come up with a good name

### ISSUE THREAD

**Issue by grantcodes** [grantcodes/net0#5]
"Sustainable Web Starter" is a fine, but not very interesting name.

I'd love to come up with an easier to remember, more unique name.

**Comment by grantcodes** [comment]
First idea that came to my mind was net0.1 which would then become net0.2 with the next version etc.

A very obvious play on the net zero emissions goal, and also internet

**Comment by w4rner** [comment]
Hard to get away from 'net zero' pun (which we decided not use for Musical in the end), though idea sounds similar to https://web0.small-web
You could deep it with a .net [domain hack](https://w4.rner.me/domainhacks) along the lines of zero.net or sustainable.net/zero for template page
.net could match the pointedly vanilla vibe

Otherwise consider following gTLDs:
 1) .BIO
2) .EARTH
3) .ECO
4) .ENERGY
6) .GREEN
7) .ORGANIC
8) .SOLAR
eg do an availability search for web keywords on those like webfor.earth or web.eco
We're likely going .earth for my Musical capstone, though doesn't look like owner they're taking any special efforts to enact their vibe into their tech.

**Comment by grantcodes** [comment]
Went with my original idea of Net0 for now, but still open to better ideas if they come up :D
